language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t atgauthier/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true atgauthier/docker-react npm run test